[mgr]

prepend_keymap = [
  { on = [ "<C-s>" ], run = "search fd", desc = "Search files by name using fd" },
  { on = [ "<C-z>" ], run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
  { on = [ "T" ], run = "plugin --sync max-preview", desc = "Maximize or restore the preview pane" },
  { on = [ "<C-n>" ], run = "plugin smart-enter", desc = "Enter hovered directory or open file" },
  { on = [ "<A-k>" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = [ "<A-j>" ], run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [ "J" ], run = "arrow 5", desc = "Move cursor down 5 lines" },
  { on = [ "<S-Tab>" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = [ "<Tab>" ], run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
  { on = [ "<C-e>" ], run = "shell '$EDITOR .' --block", desc = "Open current directory in editor" },
]

[tasks]

prepend_keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Hide the task manager" },
  { on = [ "w" ], run = "close", desc = "Hide the task manager" },
]

[select]

prepend_keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel selection" },
  { on = [ "<C-c>" ], run = "close", desc = "Cancel selection" },
]

[input]

prepend_keymap = [
  { on = [ "<C-c>" ], run = "close", desc = "Cancel input" },
  { on = [ "<C-u>" ], run = "kill bol", desc = "Kill backwards to the BOL" },
  { on = [ "<C-k>" ], run = "kill eol", desc = "Kill forwards to the EOL" },
  { on = [ "<C-h>" ], run = "backspace", desc = "Delete the character before the cursor" },
  { on = [ "<C-d>" ], run = "delete", desc = "Delete the character at the cursor" },
  { on = [ "<C-a>" ], run = "move bol", desc = "Move cursor to the beginning of line" },
  { on = [ "<C-e>" ], run = "move eol", desc = "Move cursor to the end of line" },
]

[help]

prepend_keymap = [
  { on = [ "<Esc>" ], run = "escape", desc = "Clear the filter, or hide the help" },
]
