[mgr]
layout         = [1, 4, 3]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
edit = [
  { run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
  { run = 'hx "$@"', desc = "Edit with Helix", block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
play = [
  { run = 'mpv "$@"', desc = "Play with mpv", orphan = true, for = "unix" },
]

[open]
rules = [
  { name = "*/", use = [ "edit", "open", "reveal" ] },
  
  { mime = "text/*", use = [ "edit", "reveal" ] },
  { mime = "image/*", use = [ "open", "reveal" ] },
  { mime = "video/*", use = [ "play", "reveal" ] },
  { mime = "audio/*", use = [ "play", "reveal" ] },
  { mime = "inode/x-empty", use = [ "edit", "reveal" ] },

  { mime = "application/json", use = [ "edit", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },

  { mime = "application/zip", use = [ "extract", "reveal" ] },
  { mime = "application/gzip", use = [ "extract", "reveal" ] },
  { mime = "application/x-tar", use = [ "extract", "reveal" ] },
  { mime = "application/x-bzip", use = [ "extract", "reveal" ] },
  { mime = "application/x-bzip2", use = [ "extract", "reveal" ] },
  { mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
  { mime = "application/x-rar", use = [ "extract", "reveal" ] },

  { mime = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [0, 0]
suppress_preload = false

