theme = "nord-night"

[editor]
auto-format = true
line-number = "absolute"
completion-timeout = 50
mouse = false
color-modes = true
true-color = true
cursorline = true
bufferline = "never"
end-of-line-diagnostics = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "┊"
skip-levels = 2
render = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
"C-s" = ":w"
"C-m" = "save_selection"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.g]
D = ["vsplit", "jump_view_up", "goto_definition"]

[keys.insert]
"C-s" = ":w"
A-x = "extend_to_line_bounds"
