require("claudecode").setup({})
require("opencode").setup({})
require("mini.diff").setup({})

-- vim.keymap.set("n", "<leader>ac", "<cmd>ClaudeCode<cr>", { desc = "Toggle Claude" })
-- vim.keymap.set("n", "<leader>af", "<cmd>ClaudeCodeFocus<cr>", { desc = "Focus Claude" })
-- vim.keymap.set("n", "<leader>ar", "<cmd>ClaudeCode --resume<cr>", { desc = "Resume Claude" })
-- vim.keymap.set("n", "<leader>aC", "<cmd>ClaudeCode --continue<cr>", { desc = "Continue Claude" })
-- vim.keymap.set("n", "<leader>am", "<cmd>ClaudeCodeSelectModel<cr>", { desc = "Select Claude model" })
-- vim.keymap.set("n", "<leader>ab", "<cmd>ClaudeCodeAdd %<cr>", { desc = "Add current buffer" })
-- vim.keymap.set("v", "<leader>as", "<cmd>ClaudeCodeSend<cr>", { desc = "Send to Claude" })
-- vim.keymap.set(
--   "n",
--   "<leader>as",
--   "<cmd>ClaudeCodeTreeAdd<cr>",
--   { desc = "Add file", ft = { "NvimTree", "neo-tree", "oil" } }
-- )
vim.keymap.set("n", "<leader>aa", "<cmd>ClaudeCodeDiffAccept<cr>", { desc = "Accept diff" })
vim.keymap.set("n", "<leader>ad", "<cmd>ClaudeCodeDiffDeny<cr>", { desc = "Deny diff" })
vim.keymap.set("n", "<leader>aA", function()
  require("opencode").ask()
end, { desc = "Ask opencode" })
vim.keymap.set("n", "<leader>ao", function()
  require("opencode").ask("@cursor: ")
end, { desc = "Ask opencode about this" })
vim.keymap.set("v", "<leader>ao", function()
  require("opencode").ask("@selection: ")
end, { desc = "Ask opencode about selection" })
vim.keymap.set("n", "<leader>at", function()
  require("opencode").toggle()
end, { desc = "Toggle embedded opencode" })
vim.keymap.set("n", "<leader>an", function()
  require("opencode").command("session_new")
end, { desc = "New session" })
vim.keymap.set("n", "<leader>ay", function()
  require("opencode").command("messages_copy")
end, { desc = "Copy last message" })
vim.keymap.set("n", "<S-C-u>", function()
  require("opencode").command("messages_half_page_up")
end, { desc = "Scroll messages up" })
vim.keymap.set("n", "<S-C-d>", function()
  require("opencode").command("messages_half_page_down")
end, { desc = "Scroll messages down" })
vim.keymap.set({ "n", "v" }, "<leader>ap", function()
  require("opencode").select_prompt()
end, { desc = "Select prompt" })
vim.keymap.set("n", "<leader>ae", function()
  require("opencode").prompt("Explain @cursor and its context")
end, { desc = "Explain code near cursor" })
